# Generated by Django 4.1.3 on 2022-11-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CM', '0003_videoreaction_videocomment_usercourse_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
