# Generated by Django 4.1.3 on 2022-11-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CM', '0005_alter_usercourse_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='status',
            field=models.CharField(choices=[('added', 'Đã thêm vào giỏ hàng'), ('waiting', 'Đang chờ thanh toán'), ('purchased', 'Đã thanh toán')], default='added', max_length=10),
        ),
    ]
