# Generated by Django 4.1.3 on 2022-11-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CM', '0006_alter_usercourse_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='course',
            new_name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='videos',
            field=models.ManyToManyField(to='CM.video'),
        ),
    ]
