# Generated by Django 4.1.3 on 2022-11-09 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CM', '0007_rename_course_video_courses_course_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='videos',
            field=models.ManyToManyField(blank=True, to='CM.video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='courses',
            field=models.ManyToManyField(blank=True, to='CM.course'),
        ),
    ]
