# Generated by Django 4.1.3 on 2022-11-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CM', '0008_alter_course_videos_alter_video_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereaction',
            name='rate',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
