# Generated by Django 4.1.4 on 2022-12-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CM', '0009_alter_coursereaction_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
